version: '3.8'
services:
  dynamodb:
    container_name: wallet_dynamodb
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl http://127.0.0.1:8000"]

  maintenance:
    container_name: wallet_maintenance
    image: wallet
    env_file: .env
    build:
      context: ${PWD}
      dockerfile: ${PWD}/ci/image_base/Dockerfile
      args:
        PIP_PACKAGES_FILE: ${PIP_PACKAGES_FILE}
    environment: &pay_env
      - PAY_AWS__DEFAULT__SERVICES__DYNAMODB__ENDPOINT_URL=http://dynamodb:8000
    command: sh -c "maintenance.sh"
    healthcheck:
      test: ["CMD-SHELL", "test -e .done"]
      interval: 20s
      timeout: 2s
      retries: 10


  app:
    container_name: wallet_app
    image: wallet
    env_file: .env
    ports:
      - "9003:9001"
    build:
      context: ${PWD}
      dockerfile: ${PWD}/ci/image_base/Dockerfile
      args:
        PIP_PACKAGES_FILE: ${PIP_PACKAGES_FILE}
    environment: *pay_env
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9001"]
      interval: 2s
      timeout: 2s
      retries: 10
    command: gunicorn gunicorn_app:app -c /home/httpd/conf/gunicorn/gunicorn.conf.py --workers=${PAY_GUNICORN_WORKERS:-1}
